### ISSUE TITLE
CLI `Build` error - Cannot Open vba-blocks.xlsm file

### ISSUE THREAD

**Issue by connerk** [vba-blocks/vba-blocks#14]
this is sporatic, never twice in a row.

```powershell
ERROR Failed to import project for target "Account Comparison Tool"

Failed to open workbook:
Command failed: cscript //Nologo C:/DevTools/vba-blocks/dist/run-scripts/run.vbs "excel" "C:/DevTools/vba-blocks/dist/addins/vba-blocks.xlsm" "Build.ImportGraph" "{|Q|file|Q|:|Q|C:/Users/kevin|S|conner/.vba-blocks/staging/vba-blocks-24032YDs0iEAHdXA4/Account|S|Comparison|S|Tool.xlsm|Q|,|Q|name|Q|:|Q|VBAProject|Q|,|Q|src|Q|:[{|Q|name|Q|:|Q|Compare|Q|,|Q|path|Q|:|Q|C:/Users/kevin|S|conner/.vba-blocks/staging/vba-blocks-24032YDs0iEAHdXA4/import/Compare.bas|Q|},{|Q|name|Q|:|Q|DebugTimer|Q|,|Q|path|Q|:|Q|C:/Users/kevin|S|conner/.vba-blocks/staging/vba-blocks-24032YDs0iEAHdXA4/import/DebugTimer.cls|Q|},{|Q|name|Q|:|Q|LPO_Color_Check1|Q|,|Q|path|Q|:|Q|C:/Users/kevin|S|conner/.vba-blocks/staging/vba-blocks-24032YDs0iEAHdXA4/import/LPO_Color_Check1.bas|Q|},{|Q|name|Q|:|Q|Module1|Q|,|Q|path|Q|:|Q|C:/Users/kevin|S|conner/.vba-blocks/staging/vba-blocks-24032YDs0iEAHdXA4/import/Module1.bas|Q|},{|Q|name|Q|:|Q|Review211|Q|,|Q|path|Q|:|Q|C:/Users/kevin|S|conner/.vba-blocks/staging/vba-blocks-24032YDs0iEAHdXA4/import/Review211.bas|Q|},{|Q|name|Q|:|Q|Rollup|Q|,|Q|path|Q|:|Q|C:/Users/kevin|S|conner/.vba-blocks/staging/vba-blocks-24032YDs0iEAHdXA4/import/Rollup.bas|Q|},{|Q|name|Q|:|Q|m_211Review|Q|,|Q|path|Q|:|Q|C:/Users/kevin|S|conner/.vba-blocks/staging/vba-blocks-24032YDs0iEAHdXA4/import/m_211Review.bas|Q|},{|Q|name|Q|:|Q|m_Compare|Q|,|Q|path|Q|:|Q|C:/Users/kevin|S|conner/.vba-blocks/staging/vba-blocks-24032YDs0iEAHdXA4/import/m_Compare.bas|Q|},{|Q|name|Q|:|Q|m_Rollup|Q|,|Q|path|Q|:|Q|C:/Users/kevin|S|conner/.vba-blocks/staging/vba-blocks-24032YDs0iEAHdXA4/import/m_Rollup.bas|Q|}],|Q|references|Q|:[]}"
C:\DevTools\vba-blocks\dist\run-scripts\run.vbs(40, 5) (null): The object invoked has disconnected from its clients.


    at run (C:\snapshot\vba-blocks\lib\bin\vba-blocks-build.js:1322:15)
    at <anonymous>
    at generateError (C:\snapshot\vba-blocks\lib\bin\vba-blocks-build.js:326:12)
    at targetImportFailed (C:\snapshot\vba-blocks\lib\bin\vba-blocks-build.js:311:52)
    at importTarget (C:\snapshot\vba-blocks\lib\bin\vba-blocks-build.js:1588:15)
    at <anonymous>
```

**Comment by timhall** [comment]
vba-blocks runs a little bit differently now, let me know if this is still an occasional issue
